title: Irriduino
description: Arduino project for an irrigation of a garden
name: Roberto Alonso
author:
    name: Roberto Alonso
    github: ralonsoafl
avatar: "https://avatars3.githubusercontent.com/u/3586109"
repository: ralonsoafl/Irriduino
url: "http://ralonsoafl.github.io/Irriduino"
baseurl: "/Irriduino"
logo: /assets/img/logo.png
theme: jekyll-theme-leap-day
show_downloads: true
exclude:
    - LICENSE
    - README.md
    - assets/img
