title: Irriduino

description: Arduino project for an irrigation of a garden

name: Roberto Alonso

author:
    name: Roberto Alonso
    avatar: 
    github: ralonsoafl

repository: ralonsoafl/Irriduino

logo: /assets/img/logo.png

theme: jekyll-theme-leap-day

show_downloads: true

exclude:
    - LICENSE
    - README.md
    - assets/img
